import 'dart:io';

import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

/// Why a video can't be played, from `youpipe/stream_extractor`'s error codes (docs/streaming.md).
class VideoUnavailable implements Exception {
  VideoUnavailable(this.code, this.message);

  /// `AGE_RESTRICTED`, `GEO_RESTRICTED`, `UNAVAILABLE`, `RECAPTCHA`, `BOT_CHECK`, `NO_STREAMS` or
  /// `EXTRACTION_FAILED`.
  final String code;
  final String message;

  String get friendly => switch (code) {
    'AGE_RESTRICTED' => 'This video is age-restricted',
    'GEO_RESTRICTED' => 'This video is not available in your country',
    'UNAVAILABLE' => 'This video is unavailable',
    'RECAPTCHA' => 'YouTube is rate-limiting this device. Try again later',
    'BOT_CHECK' => "YouTube wants to confirm you're not a bot. Try again in a while",
    'NO_STREAMS' => 'No playable stream for this video',
    _ => 'Couldn\'t load this video',
  };

  @override
  String toString() => 'VideoUnavailable($code): $message';
}

class CaptionTrack {
  const CaptionTrack({required this.url, required this.languageCode, required this.name, required this.autoGenerated});

  final String url;
  final String languageCode;
  final String name;
  final bool autoGenerated;
}

class Chapter {
  const Chapter(this.title, this.start, this.thumbnail);

  final String title;
  final Duration start;
  final String? thumbnail;
}

/// A storyboard level: sprite sheets of [framesPerPageX] × [framesPerPageY] frames, one per [durationPerFrame].
class Storyboard {
  const Storyboard({
    required this.urls,
    required this.frameWidth,
    required this.frameHeight,
    required this.totalCount,
    required this.durationPerFrame,
    required this.framesPerPageX,
    required this.framesPerPageY,
  });

  final List<String> urls;
  final int frameWidth;
  final int frameHeight;
  final int totalCount;
  final Duration durationPerFrame;
  final int framesPerPageX;
  final int framesPerPageY;
}

/// Everything about one video that comes from NewPipeExtractor: metadata and every way to play it.
class VideoInfo {
  VideoInfo._(this.raw, {this.manifestPath});

  /// A downloaded video's info, from the library (no network).
  VideoInfo.offline({
    required String videoId,
    required String title,
    String? channelName,
    String? channelId,
    String? channelAvatar,
  }) : this._({
         'videoId': videoId,
         'title': title,
         'channelName': channelName,
         'channelId': channelId,
         'channelAvatar': channelAvatar,
       });

  final Map<Object?, Object?> raw;

  /// The DASH manifest written to a local file, when there is one.
  final String? manifestPath;

  String get videoId => raw['videoId'] as String;
  String get title => raw['title'] as String? ?? '';
  String? get channelId => raw['channelId'] as String?;
  String get channelName => raw['channelName'] as String? ?? '';
  String? get channelAvatar => raw['channelAvatar'] as String?;
  int get subscriberCount => (raw['subscriberCount'] as num?)?.toInt() ?? -1;
  int get viewCount => (raw['viewCount'] as num?)?.toInt() ?? -1;
  int get likeCount => (raw['likeCount'] as num?)?.toInt() ?? -1;
  String? get uploadDate => raw['uploadDate'] as String?;
  String get description => raw['description'] as String? ?? '';
  Duration get duration => Duration(seconds: (raw['durationSeconds'] as num?)?.toInt() ?? 0);
  bool get isLive => raw['isLive'] == true;
  bool get isShort => raw['isShort'] == true;
  String? get hlsUrl => raw['hlsUrl'] as String?;
  String? get muxedUrl => raw['muxedUrl'] as String?;
  int? get muxedHeight => (raw['muxedHeight'] as num?)?.toInt();
  List<int> get dashHeights => (raw['dashHeights'] as List?)?.cast<int>() ?? const [];
  String? get dashCodec => raw['dashCodec'] as String?;

  /// The User-Agent each source's URLs need: they're bound to the InnerTube client that produced them, and the DASH
  /// and muxed streams can come from different clients.
  String get dashUserAgent => raw['dashUserAgent'] as String? ?? '';
  String get muxedUserAgent => raw['muxedUserAgent'] as String? ?? '';
  String get hlsUserAgent => raw['hlsUserAgent'] as String? ?? '';

  /// What can be downloaded: (height, total bytes), lowest first.
  List<(int, int)> get downloadOptions => [
    for (final o in (raw['downloadOptions'] as List? ?? const []).cast<Map>())
      ((o['height'] as num).toInt(), (o['size'] as num? ?? 0).toInt()),
  ];

  List<CaptionTrack> get captions => [
    for (final c in (raw['captions'] as List? ?? const []).cast<Map>())
      CaptionTrack(
        url: c['url'] as String,
        languageCode: c['languageCode'] as String? ?? '',
        name: c['name'] as String? ?? '',
        autoGenerated: c['autoGenerated'] == true,
      ),
  ];

  List<Chapter> get chapters => [
    for (final c in (raw['chapters'] as List? ?? const []).cast<Map>())
      Chapter(
        c['title'] as String? ?? '',
        Duration(seconds: (c['startSeconds'] as num?)?.toInt() ?? 0),
        c['thumbnail'] as String?,
      ),
  ];

  List<Storyboard> get storyboards => [
    for (final s in (raw['storyboards'] as List? ?? const []).cast<Map>())
      Storyboard(
        urls: (s['urls'] as List).cast<String>(),
        frameWidth: (s['frameWidth'] as num).toInt(),
        frameHeight: (s['frameHeight'] as num).toInt(),
        totalCount: (s['totalCount'] as num).toInt(),
        durationPerFrame: Duration(milliseconds: (s['durationPerFrameMs'] as num).toInt()),
        framesPerPageX: (s['framesPerPageX'] as num).toInt(),
        framesPerPageY: (s['framesPerPageY'] as num).toInt(),
      ),
  ];

  /// When the stream URLs stop working (their `expire` parameter), or an hour from now if they don't say.
  DateTime get expires {
    final url = muxedUrl ?? hlsUrl ?? '';
    final m = RegExp(r'[?&/]expire[=/](\d+)').firstMatch(url);
    final s = m == null ? null : int.tryParse(m.group(1)!);
    return s == null ? DateTime.now().add(const Duration(hours: 1)) : DateTime.fromMillisecondsSinceEpoch(s * 1000);
  }
}

/// Calls `youpipe/stream_extractor` and caches results until 10 minutes before their URLs expire.
class VideoInfoService {
  VideoInfoService({this.hl = 'en', this.gl = 'US'});

  static const _channel = MethodChannel('youpipe/stream_extractor');

  String hl;
  String gl;

  final _cache = <String, VideoInfo>{};
  final _pending = <String, Future<VideoInfo>>{};

  Future<VideoInfo> get(String videoId, {int maxHeight = 1080, bool forceRefresh = false}) {
    final key = '$videoId@$maxHeight';
    final cached = _cache[key];
    if (!forceRefresh &&
        cached != null &&
        DateTime.now().isBefore(cached.expires.subtract(const Duration(minutes: 10)))) {
      return Future.value(cached);
    }
    // The callback must not return the removed future: whenComplete would then wait on itself.
    return _pending[key] ??= _fetch(videoId, maxHeight, key).whenComplete(() {
      _pending.remove(key);
    });
  }

  Future<VideoInfo> _fetch(String videoId, int maxHeight, String key) async {
    Map<Object?, Object?>? raw;
    for (var attempt = 0; raw == null; attempt++) {
      try {
        raw = await _channel.invokeMapMethod<Object?, Object?>('getVideoInfo', {
          'videoId': videoId,
          'hl': hl,
          'gl': gl,
          'maxHeight': maxHeight,
        });
      } on PlatformException catch (e) {
        // YouTube now and then answers NewPipe with an HTML page instead of JSON; a second try usually works.
        if (e.code != 'EXTRACTION_FAILED' || attempt > 0) throw VideoUnavailable(e.code, e.message ?? e.code);
        await Future<void>.delayed(const Duration(seconds: 1));
      }
    }
    String? manifestPath;
    final mpd = raw['dashMpd'] as String?;
    if (mpd != null) {
      final dir = Directory('${(await getTemporaryDirectory()).path}/video');
      await dir.create(recursive: true);
      manifestPath = '${dir.path}/${videoId}_$maxHeight.mpd';
      await File(manifestPath).writeAsString(mpd);
    }
    final info = VideoInfo._(raw, manifestPath: manifestPath);
    _cache[key] = info;
    if (_cache.length > 50) _cache.remove(_cache.keys.first);
    return info;
  }

  void invalidate(String videoId) => _cache.removeWhere((k, _) => k.startsWith('$videoId@'));
}
