import 'dart:async';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_symbols_icons/symbols.dart';
import 'package:video_player/video_player.dart';

import '../../data/video_info.dart';
import '../../providers.dart';
import '../../ui/theme/yt_theme.dart';
import '../../ui/widgets/common.dart';

// Captions ------------------------------------------------------------------------------------------------------

/// The caption track shown on the current video (null = off). The chosen language carries over to the next
/// videos, like YouTube's CC button.
final captionsProvider = NotifierProvider<CaptionsController, CaptionTrack?>(CaptionsController.new);

class CaptionsController extends Notifier<CaptionTrack?> {
  static final _dio = Dio(BaseOptions(receiveTimeout: const Duration(seconds: 20)));

  @override
  CaptionTrack? build() {
    final info = ref.watch(currentInfoProvider);
    final controller = ref.watch(playerControllerProvider);
    final lang = ref.read(prefsProvider).getString('captionLang');
    if (info == null || controller == null || lang == null) return null;
    final track = pick(info.captions, lang);
    if (track != null) unawaited(_load(controller, track));
    return track;
  }

  /// The manual track in [lang] if there is one, else the auto-generated one.
  static CaptionTrack? pick(List<CaptionTrack> tracks, String lang) {
    final same = tracks.where((c) => c.languageCode.split('-').first == lang.split('-').first).toList();
    return same.where((c) => !c.autoGenerated).firstOrNull ?? same.firstOrNull;
  }

  Future<void> _load(VideoPlayerController c, CaptionTrack track) async {
    try {
      final res = await _dio.get<String>(track.url, options: Options(responseType: ResponseType.plain));
      await c.setClosedCaptionFile(Future.value(WebVTTCaptionFile(cleanVtt(res.data ?? ''))));
    } catch (e) {
      debugPrint('YouPipe: captions failed: $e');
    }
  }

  Future<void> select(CaptionTrack? track) async {
    final prefs = ref.read(prefsProvider);
    final c = ref.read(playerControllerProvider);
    if (track == null) {
      await prefs.remove('captionLang');
      await c?.setClosedCaptionFile(null);
    } else {
      await prefs.setString('captionLang', track.languageCode);
      if (c != null) await _load(c, track);
    }
    state = track;
  }
}

/// The CC button: off ↔ the last language (or the app language, or the first track).
Future<void> toggleCaptions(BuildContext context, WidgetRef ref) async {
  final info = ref.read(currentInfoProvider);
  if (info == null) return;
  final notifier = ref.read(captionsProvider.notifier);
  if (ref.read(captionsProvider) != null) {
    await notifier.select(null);
    if (context.mounted) showSnack(context, 'Captions off');
    return;
  }
  final track =
      CaptionsController.pick(info.captions, ref.read(prefsProvider).getString('captionLang') ?? '') ??
      CaptionsController.pick(info.captions, ref.read(settingsProvider).hl) ??
      info.captions.firstOrNull;
  await notifier.select(track);
  if (context.mounted && track != null) {
    showSnack(context, '${track.name}${track.autoGenerated ? ' (auto-generated)' : ''}');
  }
}

/// The caption line over the video, styled like YouTube's default (white on translucent black).
/// Strips the karaoke markup of YouTube's auto-generated tracks (`word<00:00:15.080><c> next</c>`), which
/// `WebVTTCaptionFile` would show as text.
String cleanVtt(String vtt) => vtt.replaceAll(_vttInlineTag, '');

final _vttInlineTag = RegExp(r'<(?:\d+:)?\d{2}:\d{2}\.\d{3}>|</?c(?:\.[\w.-]+)?>');

class CaptionOverlay extends StatelessWidget {
  const CaptionOverlay({super.key, required this.controller, this.bottom = 24});

  final VideoPlayerController controller;
  final double bottom;

  @override
  Widget build(BuildContext context) => ValueListenableBuilder<VideoPlayerValue>(
    valueListenable: controller,
    builder: (context, v, _) {
      final text = v.caption.text.trim();
      if (text.isEmpty) return const SizedBox.shrink();
      return Positioned(
        left: 24,
        right: 24,
        bottom: bottom,
        child: Center(
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
            color: Colors.black.withValues(alpha: 0.75),
            child: Text(
              text,
              textAlign: TextAlign.center,
              style: const TextStyle(color: Colors.white, fontSize: 15, height: 1.3),
            ),
          ),
        ),
      );
    },
  );
}

// Sleep timer ---------------------------------------------------------------------------------------------------

/// When playback should stop (null = off). `Duration.zero` means "at the end of this video".
final sleepTimerProvider = NotifierProvider<SleepTimerController, DateTime?>(SleepTimerController.new);

class SleepTimerController extends Notifier<DateTime?> {
  Timer? _timer;
  bool endOfVideo = false;

  @override
  DateTime? build() {
    ref.onDispose(() => _timer?.cancel());
    return null;
  }

  void set(Duration? d) {
    _timer?.cancel();
    endOfVideo = d == Duration.zero;
    if (d == null) {
      state = null;
      return;
    }
    if (endOfVideo) {
      state = DateTime.now();
      final svc = ref.read(playerServiceProvider);
      late final StreamSubscription<String> sub;
      sub = svc.completed.listen((_) {
        sub.cancel();
        if (endOfVideo) {
          svc.controller.value?.pause();
          state = null;
        }
      });
      return;
    }
    state = DateTime.now().add(d);
    _timer = Timer(d, () {
      ref.read(playerServiceProvider).controller.value?.pause();
      state = null;
    });
  }
}

// The settings sheet ------------------------------------------------------------------------------------------------

Future<void> showPlayerSettings(BuildContext context, WidgetRef ref) => showModalBottomSheet<void>(
  context: context,
  useRootNavigator: true,
  builder: (sheet) => Consumer(
    builder: (sheet, ref, _) {
      final c = ref.watch(playerControllerProvider);
      final info = ref.watch(currentInfoProvider);
      final svc = ref.read(playerServiceProvider);
      final caption = ref.watch(captionsProvider);
      final playing = ref.watch(playbackProvider);
      final sleep = ref.watch(sleepTimerProvider);
      final height = c?.value.size.height.round() ?? 0;
      String sub(String s) => s;
      return SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            _SettingTile(
              icon: Symbols.tune,
              label: 'Quality',
              value: sub(
                '${_qualityLabel(svc.maxHeight, ref.read(settingsProvider).quality.maxHeight)}${height > 0 ? ' (${height}p)' : ''}',
              ),
              onTap: () {
                Navigator.of(sheet).pop();
                _showQuality(context, ref, info);
              },
            ),
            _SettingTile(
              icon: Symbols.slow_motion_video,
              label: 'Playback speed',
              value: (c?.value.playbackSpeed ?? 1) == 1 ? 'Normal' : '${c!.value.playbackSpeed}x',
              onTap: () {
                Navigator.of(sheet).pop();
                _showSpeed(context, ref);
              },
            ),
            if (info != null && info.captions.isNotEmpty)
              _SettingTile(
                icon: Symbols.closed_caption,
                label: 'Captions',
                value: caption == null ? 'Off' : caption.name,
                onTap: () {
                  Navigator.of(sheet).pop();
                  _showCaptions(context, ref, info);
                },
              ),
            SwitchListTile(
              secondary: const Icon(Symbols.repeat, weight: 300),
              title: const Text('Loop video'),
              value: playing?.loop ?? false,
              onChanged: (_) => ref.read(playbackProvider.notifier).toggleLoop(),
            ),
            _SettingTile(
              icon: Symbols.bedtime,
              label: 'Sleep timer',
              value: sleep == null
                  ? 'Off'
                  : ref.read(sleepTimerProvider.notifier).endOfVideo
                  ? 'End of video'
                  : '${sleep.difference(DateTime.now()).inMinutes + 1} min',
              onTap: () {
                Navigator.of(sheet).pop();
                _showSleep(context, ref);
              },
            ),
          ],
        ),
      );
    },
  ),
);

String _qualityLabel(int current, int preferred) => switch (current) {
  1080 => 'Auto',
  2160 => 'Higher picture quality',
  480 => 'Data saver',
  _ => '${current}p',
};

class _SettingTile extends StatelessWidget {
  const _SettingTile({required this.icon, required this.label, required this.value, required this.onTap});

  final IconData icon;
  final String label;
  final String value;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) => ListTile(
    leading: Icon(icon, weight: 300),
    title: Text(label),
    trailing: Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(value, style: TextStyle(color: context.yt.textSecondary, fontSize: 13)),
        Icon(Symbols.chevron_right, color: context.yt.textSecondary),
      ],
    ),
    onTap: onTap,
  );
}

Future<void> _choose<T>(
  BuildContext context, {
  required String title,
  required List<(T, String, String?)> options,
  required T selected,
  required ValueChanged<T> onSelect,
}) => showModalBottomSheet<void>(
  context: context,
  useRootNavigator: true,
  isScrollControlled: true,
  builder: (sheet) => SafeArea(
    child: Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 8),
          child: Text(title, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500)),
        ),
        Flexible(
          child: ListView(
            shrinkWrap: true,
            children: [
              for (final (value, label, sub) in options)
                ListTile(
                  leading: SizedBox(
                    width: 24,
                    child: value == selected ? const Icon(Symbols.check, weight: 300) : null,
                  ),
                  title: Text(label),
                  subtitle: sub == null ? null : Text(sub),
                  onTap: () {
                    Navigator.of(sheet).pop();
                    onSelect(value);
                  },
                ),
            ],
          ),
        ),
      ],
    ),
  ),
);

void _showQuality(BuildContext context, WidgetRef ref, VideoInfo? info) {
  final svc = ref.read(playerServiceProvider);
  final heights = (info?.dashHeights ?? const <int>[]).where((h) => h >= 144).toList().reversed;
  _choose<int>(
    context,
    title: 'Quality for current video',
    selected: svc.maxHeight,
    options: [
      (1080, 'Auto (recommended)', 'Adjusts to give you the best experience for your conditions'),
      (2160, 'Higher picture quality', 'Uses more data'),
      (480, 'Data saver', 'Lower picture quality'),
      for (final h in heights)
        if (h != 1080 && h != 2160 && h != 480) (h, '${h}p', null),
    ],
    onSelect: (h) => svc.setMaxHeight(h),
  );
}

void _showSpeed(BuildContext context, WidgetRef ref) {
  final c = ref.read(playerControllerProvider);
  _choose<double>(
    context,
    title: 'Playback speed',
    selected: c?.value.playbackSpeed ?? 1,
    options: [
      for (final s in const [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]) (s, s == 1 ? 'Normal' : '${s}x', null),
    ],
    onSelect: (s) => c?.setPlaybackSpeed(s),
  );
}

void _showCaptions(BuildContext context, WidgetRef ref, VideoInfo info) {
  final current = ref.read(captionsProvider);
  _choose<CaptionTrack?>(
    context,
    title: 'Captions',
    selected: current,
    options: [
      (null, 'Off', null),
      for (final c in info.captions) (c, c.autoGenerated ? '${c.name} (auto-generated)' : c.name, null),
    ],
    onSelect: (c) => ref.read(captionsProvider.notifier).select(c),
  );
}

void _showSleep(BuildContext context, WidgetRef ref) {
  _choose<Duration?>(
    context,
    title: 'Sleep timer',
    selected: null,
    options: const [
      (null, 'Off', null),
      (Duration(minutes: 10), '10 minutes', null),
      (Duration(minutes: 15), '15 minutes', null),
      (Duration(minutes: 20), '20 minutes', null),
      (Duration(minutes: 30), '30 minutes', null),
      (Duration(minutes: 45), '45 minutes', null),
      (Duration(hours: 1), '60 minutes', null),
      (Duration.zero, 'End of video', null),
    ],
    onSelect: (d) {
      ref.read(sleepTimerProvider.notifier).set(d);
      showSnack(context, d == null ? 'Sleep timer off' : 'Sleep timer set');
    },
  );
}
